{{- $env := include "order-manager.env" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-manager.fullname" . }}
  labels:
    {{- include "order-manager.labels" . | nindent 4 }}
type: "kubernetes.io/storageos"
data: 
{{- with (index .Values.env $env).api -}}
{{ . | toYaml | nindent 2 }}
{{- end }}
