{{- if .Values.serviceAccount.create -}}
{{- $fullname := include "helm-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $endpoint := .Values.ingress.endpoint -}}
{{- $env := include "helm-chart.env" . -}}
{{- $instance := .Release.Name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" $instance $env }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
