{{- $fullname := include "helm-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $endpoint := .Values.ingress.endpoint -}}
{{- $env := include "helm-chart.env" . -}}
{{- $instance := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $instance $env }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
